# mappings.py

mappinguntis = {
    ord("Ë"): "E",
    ord("ë"): "e",
    ord("Ï"): "I",
    ord("ï"): "i",
    ord("Ÿ"): "Y",
    ord("ÿ"): "y",
    ord("À"): "A",
    ord("Á"): "A",
    ord("Â"): "A",
    ord("Ã"): "A",
    ord("Å"): "A",
    ord("Æ"): "Ae",
    ord("Ç"): "C",
    ord("Ì"): "I",
    ord("Í"): "I",
    ord("Î"): "I",
    ord("Ð"): "D",
    ord("Ñ"): "N",
    ord("Ò"): "O",
    ord("Ó"): "O",
    ord("Õ"): "O",
    ord("Ø"): "Oe",
    ord("Œ"): "Oe",
    ord("Ù"): "U",
    ord("Ú"): "U",
    ord("Û"): "U",
    ord("Ý"): "Y",
    ord("Þ"): "Th",
    ord("à"): "a",
    ord("á"): "a",
    ord("â"): "a",
    ord("ã"): "a",
    ord("å"): "a",
    ord("æ"): "ae",
    ord("ç"): "c",
    ord("ì"): "i",
    ord("í"): "i",
    ord("î"): "i",
    ord("ð"): "d",
    ord("ñ"): "n",
    ord("ò"): "o",
    ord("ó"): "o",
    ord("õ"): "o",
    ord("ø"): "oe",
    ord("œ"): "oe",
    ord("ù"): "u",
    ord("ú"): "u",
    ord("û"): "u",
    ord("ý"): "y",
    ord("þ"): "Th",
    ord("Š"): "S",
    ord("Ş"): "S",
    ord("š"): "s",
    ord("Č"): "C",
    ord("ă"): "a",
    ord("č"): "c",
}

mappingusername = {
    ord("Ä"): "Ae",
    ord("ä"): "ae",
    ord("Ë"): "E",
    ord("ë"): "e",
    ord("Ï"): "I",
    ord("ï"): "i",
    ord("Ö"): "Oe",
    ord("ö"): "oe",
    ord("Ü"): "Ue",
    ord("ü"): "ue",
    ord("Ÿ"): "Y",
    ord("ÿ"): "y",
    ord("ß"): "ss",
    ord("À"): "A",
    ord("Á"): "A",
    ord("Â"): "A",
    ord("Ã"): "A",
    ord("Å"): "A",
    ord("Æ"): "Ae",
    ord("Ç"): "C",
    ord("È"): "E",
    ord("É"): "E",
    ord("Ê"): "E",
    ord("Ì"): "I",
    ord("Í"): "I",
    ord("Î"): "I",
    ord("Ð"): "D",
    ord("Ñ"): "N",
    ord("Ò"): "O",
    ord("Ó"): "O",
    ord("Ô"): "O",
    ord("Õ"): "O",
    ord("Ø"): "Oe",
    ord("Œ"): "Oe",
    ord("Ù"): "U",
    ord("Ú"): "U",
    ord("Û"): "U",
    ord("Ý"): "Y",
    ord("Þ"): "Th",
    ord("à"): "a",
    ord("á"): "a",
    ord("â"): "a",
    ord("ã"): "a",
    ord("å"): "a",
    ord("æ"): "ae",
    ord("ç"): "c",
    ord("è"): "e",
    ord("é"): "e",
    ord("ê"): "e",
    ord("ì"): "i",
    ord("í"): "i",
    ord("î"): "i",
    ord("ð"): "d",
    ord("ñ"): "n",
    ord("ò"): "o",
    ord("ó"): "o",
    ord("ô"): "o",
    ord("õ"): "o",
    ord("ø"): "oe",
    ord("œ"): "oe",
    ord("ù"): "u",
    ord("ú"): "u",
    ord("û"): "u",
    ord("ý"): "y",
    ord("þ"): "Th",
    ord("Š"): "S",
    ord("Ş"): "S",
    ord("š"): "s",
    ord("Č"): "C",
    ord("ă"): "a",
    ord("č"): "c",
    ord("ọ"): "o",
    ord("ş"): "s",
}

mappingklassen = {
    "05BS": "5b",
    "05AS": "5a",
    "05CS": "5c",
    "05DS": "5d",
    "05ES": "5e",
    "06AS": "6a",
    "06BS": "6b",
    "06CS": "6c",
    "06DS": "6d",
    "06ES": "6e",
    "07AS": "7a",
    "07BS": "7b",
    "07CS": "7c",
    "07DS": "7d",
    "07ES": "7e",
    "08AS": "8a",
    "08BS": "8b",
    "08CS": "8c",
    "08DS": "8d",
    "08ES": "8e",
    "09AS": "9a",
    "09BS": "9b",
    "09CS": "9c",
    "09DS": "9d",
    "09ES": "9e",
    "10AS": "10a",
    "10BS": "10b",
    "10CS": "10c",
    "10DS": "10d",
    "10ES": "10e",
    "EFS": "EF",
    "Q1S": "Q1",
    "Q2S": "Q2",
    "WKS": "WK",
    "TKS": "TK",
}


mapping_email_kuerzel = {
    
}


mapping_kuerzel_email = {
   
}


mappinggroups = {
    "Fach Biologie": "",
    "Fach Biologie - Lehrer": "FS-Bio",
    "Fach Bio: Mensch u. Umwelt": "",
    "Fach Bio: Mensch u. Umwelt - Lehrer": "",
    "Fach Chemie": "",
    "Fach Chemie - Lehrer": "FS-Ch",
    "Fach Deutsch": "",
    "Fach Deutsch - Lehrer": "FS-D",
    "Fach Englisch": "",
    "Fach Englisch - Lehrer": "FS-E",
    "Fach Englisch, Beginn in Jahrgangsklasse 5": "",
    "Fach Englisch, Beginn in Jahrgangsklasse 5 - Lehrer": "",
    "Fach Erdkunde": "",
    "Fach Erdkunde - Lehrer": "FS-Ek",
    "Fach Erdkunde ABI-Bac": "",
    "Fach Erdkunde ABI-Bac - Lehrer": "FS-Abi-Bac",
    "Fach evangelische Religionslehre": "",
    "Fach evangelische Religionslehre - Lehrer": "FS-eR",
    "Fach Französisch": "",
    "Fach Französisch - Lehrer": "FS-F",
    "Fach Französisch, Beginn in Jahrgangsstufe 5": "",
    "Fach Französisch, Beginn in Jahrgangsstufe 5 - Lehrer": "",
    "Fach Französisch, Beginn in Jahrgangsstufe 6": "",
    "Fach Französisch, Beginn in Jahrgangsstufe 6 - Lehrer": "",
    "Fach Französisch, Beginn in Jahrgangsklasse 7": "",
    "Fach Französisch, Beginn in Jahrgangsklasse 7 - Lehrer": "",
    "Fach Französisch, Beginn in Jahrgangsklasse 9": "",
    "Fach Französisch, Beginn in Jahrgangsklasse 9 - Lehrer": "",
    "Fach Französisch AbiBac": "",
    "Fach Französisch AbiBac - Lehrer": "",
    "Fach Geschichte": "",
    "Fach Geschichte - Lehrer": "FS-G",
    "Fach Geschichte ABI-Bac": "",
    "Fach Geschichte ABI-Bac - Lehrer": "",
    "Fach Muttersprache anstelle einer Pflichtfremdsprache - Griechisch": "",
    "Fach Muttersprache anstelle einer Pflichtfremdsprache - Griechisch - Lehrer": "",
    "Fach Jüdische Religionslehre": "",
    "Fach Jüdische Religionslehre - Lehrer": "",
    "Fach Italienisch": "",
    "Fach Italienisch - Lehrer": "FS-I",
    "Fach Informatik": "",
    "Fach Informatik - Lehrer": "FS-Inf",
    "Fach Japanisch, Beginn in Jahrgangsklasse 10": "",
    "Fach Japanisch, Beginn in Jahrgangsklasse 10 - Lehrer": "",
    "Fach katholische Religionslehre": "",
    "Fach katholische Religionslehre - Lehrer": "FS-kR",
    "Fach Kunsterziehung": "",
    "Fach Kunsterziehung - Lehrer": "FS-Ku",
    "Fach Latein": "",
    "Fach Latein - Lehrer": "FS-L",
    "Fach Lateinisch, Beginn in Jahrgangsklasse 6": "",
    "Fach Lateinisch, Beginn in Jahrgangsklasse 6 - Lehrer": "",
    "Fach Lateinisch, Beginn in Jahrgangsklasse 7": "",
    "Fach Lateinisch, Beginn in Jahrgangsklasse 7 - Lehrer": "",
    "Fach Mathematik": "",
    "Fach Mathematik - Lehrer": "FS-M",
    "Fach Musik": "",
    "Fach Musik - Lehrer": "FS-Mu",
    "Fach Naturwissenschaften": "",
    "Fach Naturwissenschaften - Lehrer": "FS-NW",
    "Fach Physik": "",
    "Fach Physik - Lehrer": "FS-Ph",
    "Fach Politik": "",
    "Fach Politik - Lehrer": "FS-SW",
    "Fach Projektkurs Wirtschaftsenglisch": "",
    "Fach Projektkurs Wirtschaftsenglisch - Lehrer": "",
    "Fach Philosophie": "",
    "Fach Philosophie - Lehrer": "FS-Pl",
    "Fach Praktische Philosophie": "",
    "Fach Praktische Philosophie - Lehrer": "FS-Pl",
    "Fach Russisch, Beginn in Jg. 10": "",
    "Fach Russisch, Beginn in Jg. 10 - Lehrer": "",
    "Fach Spanisch, Beginn in Jahrgangsklasse 8": "",
    "Fach Spanisch, Beginn in Jahrgangsklasse 8 - Lehrer": "",
    "Fach Schwimmen": "",
    "Fach Schwimmen - Lehrer": "",
    "Fach Sport": "",
    "Fach Sport - Lehrer": "FS-Sp",
    "Fach Sozialwissenschaften": "",
    "Fach Sozialwissenschaften - Lehrer": "FS-SW",
    "Fach Türkisch, Beginn in Jahrgangsklasse 8": "",
    "Fach Türkisch, Beginn in Jahrgangsklasse 8 - Lehrer": "",
    "Fach Unesco": "",
    "Fach Unesco - Lehrer": "FS-UN",
    "Fach VT Deutsch": "",
    "Fach VT Deutsch - Lehrer": "",
    "Fach VT Englisch": "",
    "Fach VT Englisch - Lehrer": "",
    "Fach MINT": "MINT",
    "Fach MINT - Lehrer": "FS-MINT",
    "Fach MINT - Schueler": "",
    "Fach VT Mathematik": "",
    "Fach VT Mathematik - Lehrer": "",
    "Gruppe Zustimmung-Presse-und-TV": "",
    "Gruppe Zustimmung-Presse-und-TV - Mitglieder": "",
    "Fach Foto AG": "",
    "Fach Foto AG - Lehrer": "",
    "Fach Theater AG": "",
    "Fach VT Französisch": "",
    "Fach VT Französisch - Lehrer": "",
    "Fach Theater AG - Lehrer": "",
    "Bereich Oberstufe - Lehrer": "Sek2-L",
    "Bereich Oberstufe": "",
    "Bereich Oberstufe - Bereichsleiter": "",
    "Fach Projektkurs Jugend forscht": "",
    "Fach Projektkurs Jugend forscht - Lehrer": "",
    "Fach Russisch, Beginn in Jahrgangsklasse 8": "",
    "Fach Russisch, Beginn in Jahrgangsklasse 8 - Lehrer": "",
    "Fach VT Mathe Ergänzung": "M-VT-S",
    "Fach VT Mathe Ergänzung - Lehrer": "M-VT-L",
    "Bereich Oberstufe - Schueler": "Sek2-S",
    "Fach Deutsch als Zielsprache": "DaZS",
    "Fach Deutsch als Zielsprache - Lehrer": "DaZS-L",
    "Fach Projektkurs": "",
    "Fach Projektkurs - Lehrer": "",
    "Fach EKF": "",
    "Fach EKF - Lehrer": "",
    "Fach GEF": "",
    "Fach GEF - Lehrer": "",
    "Fach VNW": "",
    "Fach VNW - Lehrer": "",
    "Fach VT Jugend forscht": "VT-JuFo",
    "Fach VT Jugend forscht - Lehrer": "VT-JuFo-L",
}
